server:
  port: 5000

security:
  oauth2:
    client:
      id: eve
      client-id:
      client-secret:
      grant-type: authorization_code
      user-authorization-uri: https://login.eveonline.com/v2/oauth/authorize
      access-token-uri: https://login.eveonline.com/v2/oauth/token
      pre-established-redirect-uri: http://localhost:5000/login/oauth2/code/
      use-current-uri: false
      scope:
        - publicData
        - esi-markets.structure_markets.v1
        - esi-characters.read_standings.v1
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      user-info-uri: https://login.eveonline.com/oauth/verify
      token-info-uri: https://login.eveonline.com/oauth/verify
      #preferTokenInfo: false
spring:
  #main:
  #  allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          evesso:
            authorization-grant-type: authorization_code
            client-id:
            client-secret:
            redirect-uri:  http://localhost:5000/login/oauth2/code/
            client-authentication-method: basic
            scope:
              - publicData
              - esi-markets.structure_markets.v1
              - esi-characters.read_standings.v1
        provider:
          evesso:
            authorization-uri: https://login.eveonline.com/v2/oauth/authorize
            token-uri: https://login.eveonline.com/v2/oauth/token
            user-info-uri: https://login.eveonline.com/oauth/verify
            user-name-attribute: CharacterID
logging:
  level:
    root: info